### ISSUE TITLE
[시작하기] 부모앱 사용자 네이버 계정 로그인 확인

### ISSUE THREAD

**Issue by khoh123** [w-labs-project/Central#16]
## User Story
- 부모앱 사용자는 네이버 계정으로 로그인 할 수 있다.

## UI/UX 
- 기획서 링크

## UAT Checklist
- [x] BI이미지 및 SNS(네이버/페이스북) 쇼셜 로그인 페이지 화면 노출 확인
- [ ] 네이버앱으로 간편 로그인 확인
- [ ] 개인정보 취급방침 동의 시 서비스 약관 화면출력 확인 
- [ ] 네이버앱 간편로그인 미사용 시 로그인 확인
- [ ] 서비스 약관 문구 노출 확인
- [ ] 네이버앱 미 설치 시 로그인 확인
- [ ] 서비스 약관 문구 노출 확인
 
## UAT TestCase
- [C-App-OnBording TestCase_v1.0](https://github.com/w-labs-project/Central/blob/master/C-App-TestCase/01.%20OnBording/UAT_C-APP_OnBoarding_TestCase_v1.0.xlsx)

## OS Version Check 
- [ ] Android 
- [ ] IOS
- [ ] Android + IOS

## 참고 사항

~테스트케이스는 업데이트 필요함~ >전체 케이스 완료 후 업데이트 예정
` TestCase v1.0`
