### ISSUE TITLE
최초 네이버 계정 부모앱 사용자 서비스 가입 확인

### ISSUE THREAD

**Issue by khoh123** [w-labs-project/Central#17]
## User Story
- 최초로 사용된 네이버 계정을 입력한 부모앱 사용자는, 서비스에 가입할 수 있다

## UI/UX 
- 기획서 링크

## UAT Checklist
- Depth Information  : 기기변경

- [ ] 모든 약관항목 [√]버튼 선택 시 각 약관항목 체크 확인
- [ ] 각 약관항목 [>]버튼 선택 시 세부내용 출력 확인
- [ ] 세부내용 화면 > [<-]버튼 선택 시 약관동의 화면복귀 확인
- [ ] 세부내용 화면 > AND Back key선택 시 약관동의 화면 복귀 확인
- [ ] [x]버튼 선택 시 서비스 약관 화면 복귀 확인
- [ ] AND Back key선택 시 서비스 약관 화면 복귀 확인
- [ ] 모든 약관항목 선택 > [동의합니다]버튼 선택 시 보호자 정보입력화면 출력 확인
- [ ] 프로필 이미지 선택 시 선택 팝업창 출력확인
- [ ] [취소]버튼 선택 시 팝업창 닫힘 확인
- [ ] 딤드처리영역 선택 시 팝업창 닫힘 확인
- [ ] AND Back key선택 시 팝업창 닫힘 확인
- [ ] [앨범에서 선택]버튼 선택 시 앨범출력 확인 
- [ ] 이미지 용량 큰 파일 선택 시 실패 메시지 출력 확인
- [ ] [사진촬영]버튼 선택 시 카메라모듈 실행확인
- [ ] 사진촬영 후 [저장] 버튼 선택 시 프로필 이미지 변경 확인
- [ ] 프로필 디폴트 이미지 변경 확인
- [ ] 보호자 이름 5자 초과입력 시 에러메시지 출력 확인
- [ ] 보호자 이름 필드값 수정 시 다음버튼 활성화 확인
- [ ] 보호자 이름 특수문자 입력시 에러메시지 출력확인
- [ ] 보호자 이름 이모지 입력 시 에러메시지 출력확인
- [ ] 올바르지 않은 휴대폰 번호 입력(11자리 초과) 시 에러메시지 출력확인
- [ ] 올바르지 않은 휴대폰 번호 입력(11자리 미만) 시 에러메시지 출력확인
- [ ] 올바르지 않은 휴대폰 번호 입력(유선번호) 시 에러메시지 출력확인
- [ ] 정상정보 입력 시 다음단계 진입확인
- [ ] QR코드 가이드화면 출력 확인
- [ ] QR코드 오입력 시 에러메시지 출력 확인
- [ ] QR코드 유효시간 초과 시 에러메시지 출력 확인
- [ ] QR코드 화면 > AND Back key시 팝업창 출력 확인
- [ ] QR코드 화면 > AND Back key > [취소]선택 시 QR코드 스캔화면 복귀 확인
- [ ] QR코드 화면 > AND Back key > [나가기]선택 시 앱종료 확인

## UAT TestCase
- [C-App-OnBording TestCase_v1.0](https://github.com/w-labs-project/Central/blob/master/C-App-TestCase/01.%20OnBording/UAT_C-APP_OnBoarding_TestCase_v1.0.xlsx)

## OS Version Check 
- [ ] Android 
- [ ] IOS
- [ ] Android + IOS
