### ISSUE TITLE
EPIC Template.

### ISSUE THREAD

**Issue by khoh123** [w-labs-project/Central#22]
## User Story
- 법정대리인 또는 위치조회 권한을 보유한 일반보호자 자격의 부모앱 사용자는 해당 워치의 내 장소 중 집 항목을 설정할 수 있다.
> 내장소가 저장되면 법정대리인, 위치조회권한 있는 보호자에게 해당 봇 메시지 발송

## UI/UX 
- [내장소 등록](https://projects.invisionapp.com/d/main#/projects/boards/5444033/167761424)
- [장소검색](https://projects.invisionapp.com/d/main#/projects/boards/5444033/166950751)
- [이름입력](https://projects.invisionapp.com/d/main#/projects/boards/5444033/167761425)
- [설정보드 구성](https://projects.invisionapp.com/d/main#/projects/boards/5444033/167761427)
- [설정보드 동작정의](https://projects.invisionapp.com/d/main#/projects/boards/5444033/167761428)
- [등록완료](https://projects.invisionapp.com/d/main#/projects/boards/5444033/167761429)
- [장소명 표시규칙 참고](https://projects.invisionapp.com/d/main#/projects/boards/5444033/167348286)
- [봇메시지_내장소 추가 참고](https://docs.google.com/spreadsheets/d/1qyV1STm52hQsehJpN5mAlTM9XIHgFZ6lI-mZV4C3KK4/edit#gid=52259368)
## UAT Checklist
- Depth Information  : 내장소 /  장소 추가

- [ ] 우리집 등록 선택 시 내장소등록 화면 출력 확인
- [ ] 최초 표시 위치는 진입 시점의 워치 최근 측위 장소 표시 확인
- [ ] 지도 드래그하여 핀 위치 조정 확인
- [ ] 지도 드래그하여 핀 위치 조정 시 POI및 주소 표시 확인
- [ ] `검색 이력이 없는 경우 히스토리 노출 영역 확인`
- [ ] `검색 이력이 있는 경우 최대 10개만 노출 되는지 확인`
- [ ] `지도상에서 드래그로 찍힌 장소가 히스토리 제외 되는지 확인`
- [ ] 주소검색창 선택 시 키보드 출력 확인
- [ ] 주소 입력 중 키워드가 이전 검색결과와 일부 일치하는 경우 우선적으로 노출 확인
- [ ] 주소 입력 중 키워드가 다수인 경우 최신 검색순으로 출력 확인
- [ ] 주소 입력 중 일치하는 키워드 하이라이트 표시 확인
- [ ] "X'버튼 선택 시 입력내용 삭제 확인
- [ ] 상단 "<-"버튼 선택 시 이전화면으로 돌아가는지 확인
- [ ] 주소입력 > 검색버튼 선택 시 검색결과 리스트에 장소명+건물종류+주소명까지 노출 확인
- [ ] `검색 결과에서 최근 측위된 워치의 위치 중심 + 관련도 순 노출되는지 확인`
- [ ] 리스트 출력 -> 스크롤 시 20개씩 불러오기 확인
- [ ] ~검색된 리스트에서 우리집 입력 상태 출력 확인~ >?
- [ ] `검색된 리스트에서 선택 시 보드가 펼쳐진 상태로 입력적용 확인`
- [ ] `설정보드가 다 펼쳐진 상태에서 지도 드래그 불가한지 확인`
- [ ] `우리집 장소명이 입력된 상태인지 확인`
- [ ] 5자 초과 입력 시 텍스트 입력불가 처리 확인
- [ ] 특수문자 입력 시 에러메시지 출력확인
- [ ] 이모지 입력 시 에러메시지 출력확인
- [ ] "x"버튼 선택 시 입력내용 삭제 확인
- [ ] 등록 중 이탈 시 팝업창 출력 확인
- [ ]  `데이터 등록없이 바로 이탈 시 팝업없이 바로 돌아가는지 확인`
- [ ] 확인 팝업창 > 취소 선택 시 이전화면으로 돌아가는지 확인
- [ ] 확인 팝업창 > 저장 시 동일 장소 존재 시 나가기 선택 후 이탈 화면 얼롯 확인
- [ ] 모든필드 정상입력 후 저장 시 내장소 화면 출력 확인
- [ ] 우리집 등록 완료 시 저장화면의 POI/주소 긴 경우 (..)말줄임 표시 출력 확인
- [ ] 우리집 등록 완료 시 법정대리인, 위치권한 있는 보호자 내장소 추가 봇 메시지 발송 확인

## UAT TestCase
- TestCase 링크

## OS Version Check 
- [ ] Android 
- [ ] IOS
- [ ] Android + IOS
